<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
        <UserSecretsId>d9936e64-1459-4dc9-8a2f-c98bc84177a8</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all"/>
        <PackageReference Include="Telerik.UI.for.Blazor" Version="15.0.1" />
    </ItemGroup>

</Project>
